// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtD6Mmytx3FdDqrOjBkL3Ag_rRGTjx0P4',
    appId: '1:229197922539:web:bb08571fdddfb6a1fafeae',
    messagingSenderId: '229197922539',
    projectId: 'teststore-bb8d1',
    authDomain: 'teststore-bb8d1.firebaseapp.com',
    storageBucket: 'teststore-bb8d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaqCwGGk3xDUEy3R9IxEWyk-E5fwPWTM4',
    appId: '1:229197922539:android:b7657ffbaa88b090fafeae',
    messagingSenderId: '229197922539',
    projectId: 'teststore-bb8d1',
    storageBucket: 'teststore-bb8d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnCJHMQAjRzwIAF8sHEGY4vT_G1ex6pmc',
    appId: '1:229197922539:ios:cd414457eedbdcd8fafeae',
    messagingSenderId: '229197922539',
    projectId: 'teststore-bb8d1',
    storageBucket: 'teststore-bb8d1.appspot.com',
    androidClientId: '229197922539-battim1og13c97vqac7jq7d6gv9p6k4k.apps.googleusercontent.com',
    iosClientId: '229197922539-rs5n2v4vt5n5868f4esrr5k97ak3ss1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeNew',
  );
}
